package com.kharcha.data

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [
        RawMessage::class,
        TransactionEntity::class,
        CategoryEntity::class,
        RuleEntity::class,
        BudgetEntity::class,
        BudgetAlertStateEntity::class
    ],
    version = 2,
    exportSchema = true
)
@TypeConverters(Converters::class)
abstract class KharchaDatabase : RoomDatabase() {
    abstract fun rawMessageDao(): RawMessageDao
    abstract fun transactionDao(): TransactionDao
    abstract fun categoryDao(): CategoryDao
    abstract fun ruleDao(): RuleDao
    abstract fun budgetDao(): BudgetDao
    abstract fun budgetAlertStateDao(): BudgetAlertStateDao

    companion object {
        /** Task 11: adds the budget-alert fire-once-per-month state table. */
        val MIGRATION_1_2: Migration = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "CREATE TABLE IF NOT EXISTS `budget_alert_states` (" +
                        "`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                        "`categoryId` INTEGER NOT NULL, " +
                        "`currency` TEXT NOT NULL, " +
                        "`yearMonth` TEXT NOT NULL, " +
                        "`thresholdFired` INTEGER NOT NULL, " +
                        "`exceededFired` INTEGER NOT NULL)"
                )
                db.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS `index_budget_alert_states_categoryId_currency_yearMonth` " +
                        "ON `budget_alert_states` (`categoryId`, `currency`, `yearMonth`)"
                )
            }
        }
        /**
         * Inserts [SeedData.CATEGORIES] and [SeedData.RULES] the moment the
         * database file is first created — never on subsequent opens. Pass
         * to `Room.databaseBuilder(...).addCallback(seedCallback)`.
         *
         * Uses raw SQL rather than the generated DAOs because `onCreate` runs
         * synchronously on the SQLite connection before Room hands back the
         * database instance the DAOs would need.
         */
        val seedCallback: RoomDatabase.Callback = object : RoomDatabase.Callback() {
            override fun onCreate(db: SupportSQLiteDatabase) {
                super.onCreate(db)
                db.beginTransaction()
                try {
                    // Categories are inserted in SeedData.CATEGORIES order so
                    // their autogenerated ids (1..N) match the ids SeedData.RULES
                    // references.
                    for (category in SeedData.CATEGORIES) {
                        db.execSQL(
                            "INSERT INTO categories (name, colorArgb, isIncome, isFee) VALUES (?, ?, ?, ?)",
                            arrayOf(category.name, category.colorArgb, if (category.isIncome) 1 else 0, if (category.isFee) 1 else 0)
                        )
                    }
                    for (rule in SeedData.RULES) {
                        db.execSQL(
                            "INSERT INTO rules (matchPattern, matchesPrefix, categoryId, priority) VALUES (?, ?, ?, ?)",
                            arrayOf(rule.matchPattern, if (rule.matchesPrefix) 1 else 0, rule.categoryId, rule.priority)
                        )
                    }
                    db.setTransactionSuccessful()
                } finally {
                    db.endTransaction()
                }
            }
        }
    }
}
