package com.kharcha.data

/**
 * Categories and rules inserted once, on first database creation, via
 * [KharchaDatabase]'s Room `onCreate` callback. Category ids below are the
 * autogenerate insertion order (1-based, matching [CATEGORIES] order) and
 * are only valid because they are inserted into an empty table in this
 * exact order.
 */
object SeedData {

    // Warm-tinted palette (ARGB), matching the app's design system — no pure
    // gray or pure black anywhere.
    private const val FOOD_DINING_COLOR = 0xFFE8734A.toInt()
    private const val GROCERIES_COLOR = 0xFF6FA96B.toInt()
    private const val SHOPPING_COLOR = 0xFFC968A6.toInt()
    private const val TRANSPORT_COLOR = 0xFF4E8FBF.toInt()
    private const val BILLS_UTILITIES_COLOR = 0xFFCC9A3D.toInt()
    private const val FEES_COLOR = 0xFFB5533F.toInt()
    private const val INCOME_COLOR = 0xFF4FA37D.toInt()
    private const val TRANSFERS_COLOR = 0xFF7C7EC2.toInt()
    private const val OTHER_COLOR = 0xFF9C7A5C.toInt()

    // Insertion order defines the autogenerated ids (1-9) used by RULES below.
    val CATEGORIES: List<CategoryEntity> = listOf(
        CategoryEntity(name = "Food & Dining", colorArgb = FOOD_DINING_COLOR, isIncome = false, isFee = false),
        CategoryEntity(name = "Groceries", colorArgb = GROCERIES_COLOR, isIncome = false, isFee = false),
        CategoryEntity(name = "Shopping", colorArgb = SHOPPING_COLOR, isIncome = false, isFee = false),
        CategoryEntity(name = "Transport", colorArgb = TRANSPORT_COLOR, isIncome = false, isFee = false),
        CategoryEntity(name = "Bills & Utilities", colorArgb = BILLS_UTILITIES_COLOR, isIncome = false, isFee = false),
        CategoryEntity(name = "Fees", colorArgb = FEES_COLOR, isIncome = false, isFee = true),
        CategoryEntity(name = "Income", colorArgb = INCOME_COLOR, isIncome = true, isFee = false),
        CategoryEntity(name = "Transfers", colorArgb = TRANSFERS_COLOR, isIncome = false, isFee = false),
        CategoryEntity(name = "Other", colorArgb = OTHER_COLOR, isIncome = false, isFee = false)
    )

    private const val FEES_ID = 6L
    private const val INCOME_ID = 7L

    val RULES: List<RuleEntity> = listOf(
        // Withholding tax withheld by the bank is a fee, not discretionary spend.
        RuleEntity(matchPattern = "WTax.Pd", matchesPrefix = true, categoryId = FEES_ID, priority = 100),
        // Interest the bank pays out is income.
        RuleEntity(matchPattern = "Int.Pd", matchesPrefix = true, categoryId = INCOME_ID, priority = 100),
        // Any remark ending in "Charge" (e.g. "cIPS Fund Trf Charge") is a bank fee.
        RuleEntity(matchPattern = "Charge", matchesPrefix = false, categoryId = FEES_ID, priority = 90)
    )
}
